# Generated by Django 3.0.7 on 2021-04-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='link',
            new_name='carlink',
        ),
    ]
