# Generated by Django 3.0.7 on 2020-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='backgroundimage',
            field=models.ImageField(default='Cbdefault.png', upload_to='cat_pics'),
        ),
        migrations.AlterField(
            model_name='category',
            name='profileimage',
            field=models.ImageField(default='Cpdefault.png', upload_to='cat_pics'),
        ),
    ]
