# Generated by Django 3.0.7 on 2020-07-23 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedusers',
            field=models.ManyToManyField(related_name='likerusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authoruser', to=settings.AUTH_USER_MODEL),
        ),
    ]
