# Generated by Django 3.0.7 on 2020-07-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0004_auto_20200724_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likedusers',
            field=models.ManyToManyField(related_name='commentlikerusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentauthoruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postauthoruser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likedusers',
            field=models.ManyToManyField(related_name='postlikerusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
