# Generated by Django 3.0.7 on 2020-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200724_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carouselimage',
            field=models.ImageField(default='Cbdefault.png', upload_to='carousel_pics'),
        ),
    ]
