# Generated by Django 3.0.7 on 2021-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
